### ISSUE TITLE
Слава Україні!

### ISSUE THREAD

**Issue by balbulator** [kvazis/newHA#2]
Шановний Олексій!
Ми вдячні Вам за вашу роботу.
Зброїні сили України висловлюють Вам особисту подяку за Ваш інтелектуальний внесок у розвиток України.
Слава Україні!

**Comment by kvazis** [comment]
> Шановний Олексій! Ми вдячні Вам за вашу роботу. Зброїні сили України висловлюють Вам особисту подяку за Ваш інтелектуальний внесок у розвиток України. Слава Україні!

Героям слава !!
